name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r agents/requirements.txt
          # ensure test runner is available in case it's not in requirements
          pip install pytest

      - name: Run pytest
        run: |
          PYTHONPATH=agents pytest -q

      - name: Fix missing .gitmodules (if any)
        run: |
          # Some runners may fail during post-checkout if a submodule entry exists but .gitmodules is absent.
          # Create an empty .gitmodules file to avoid fatal errors during cleanup.
          if [ ! -f .gitmodules ] && git ls-files --error-unmatch icp_canister > /dev/null 2>&1; then
            echo "" > .gitmodules
            git add .gitmodules || true
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build
