name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # don't try to initialize submodules (icp_canister appears to be a stale submodule entry)
          submodules: false

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'


      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          # install project deps and the async pytest plugins the tests expect
          pip install -r agents/requirements.txt pytest pytest-asyncio anyio

      - name: Run pytest
        run: |
          PYTHONPATH=agents pytest -q



      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build frontend
        working-directory: frontend
        run: |
          npm ci
          # Run frontend tests in CI (vitest) before build
          npm ci
          npm test --silent
          npm run build
