name: Frontend CI

on:
  pull_request:
    paths:
      - 'frontend/**'
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          # Detect whether frontend exists at ./frontend or in repo root and install accordingly
          DIR=./frontend
          if [ ! -d "$DIR" ]; then
            DIR=.
          fi
          echo "Installing frontend dependencies in $DIR"
          cd "$DIR"
          npm ci --legacy-peer-deps --no-audit --no-fund

      - name: Build frontend
        run: |
          DIR=./frontend
          if [ ! -d "$DIR" ]; then
            DIR=.
          fi
          echo "Building frontend in $DIR"
          cd "$DIR"
          npm run build
